manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: TKBxcl32
      url-base: https://github.com/TKBxcl32
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: TKBxcl32
      revision: main
  self:
    path: config
